---
- name: config | Configuring Redis
  template:
    dest: "{{ redis_conf }}"
    group: "{{ redis_user_info.group }}"
    mode: u=rw,g=r,o=
    owner: "{{ redis_user_info.name }}"
    src: etc/redis/redis.conf.j2
  become: true
  notify:
    - restart redis

- name: config | Configuring Sysctl Settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  become: true
  notify:
    - restart redis
  loop: "{{ redis_sysctl_settings }}"
  when: redis_sysctl_settings != []
