---
- name: debian | Installing Pre-Reqs
  apt:
    name:
      - ruby
      - rubygems-integration
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing Redis
  apt:
    name: redis-server
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing Redis Sentinel
  apt:
    name: redis-sentinel
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - redis_replication|bool
