---
- name: redhat | Installing Pre-Reqs
  package:
    name:
      - ruby
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | Installing Redis
  package:
    name: redis
    state: present
  become: true
  register: result
  until: result is successful
