---
# handlers file for ansible-redis
- name: restart redis
  service:
    name: redis
    state: restarted
  become: true

- name: restart redis-server
  service:
    name: redis-server
    state: restarted
  become: true

- name: restart sentinel
  service:
    name: sentinel
    state: restarted
  become: true
