---
- name: Converge
  hosts: all
  vars:
    redis_bind_addresses:
      - 0.0.0.0
    redis_config_redis: true
  tasks:
    - name: Include ansible-redis
      include_role:
        name: ansible-redis
