---
- hosts: all
  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Include ansible-bootstrap-python
      include_role:
        name: mrlesmithjr.ansible_bootstrap_python
